#!/usr/bin/env bash
# This script answers multiple choice questions about network types.

# Answer for the first question: What type of network is a computer in local connected to? (LAN)
echo "3" 

# Answer for the second question: What type of network could connect an office in one building to another office in a building a few streets away? (LAN)
echo "3"

# Answer for the third question: What network do you use when you browse www.google.com from your smartphone (not connected to WiFi)? (WAN)
echo "2"
