#!/usr/bin/env bash
# This script answers multiple choice questions about UDP and TCP protocols.

# Answer for the first question: Which statement is correct for the TCP box? (It is a protocol that is transferring data in a slow way but surely)
echo "1"

# Answer for the second question: Which statement is correct for the UDP box? (It is a protocol that is transferring data in a fast way and might lose data along in the process)
echo "2"

# Answer for the third question: Which statement is correct for the TCP worker? (Have you received boxes x, y, z?)
echo "1"
